name: 'Baidu Tieba Auto Sign'

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 19 * * *'
  workflow_dispatch: {}
    
jobs:
  tieba_sign:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout codes'
        uses: actions/checkout@v4
      - name: 'Set python'
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: 'Install dependencies'
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade requests PySocks aiohttp aiotieba
      - name: 'Start Sign'
        env:
          BDUSS: ${{ secrets.BDUSS }}
          STOKEN: ${{ secrets.STOKEN }}
          PUSHPLUS_TOKEN: ${{ secrets.PUSHPLUS_TOKEN }}
          HOST: ${{ secrets.HOST }}
          FROM: ${{ secrets.FROM }}
          TO: ${{ secrets.TO }}
          AUTH: ${{ secrets.AUTH }}
          MODERATED_BARS: ${{ secrets.MODERATED_BARS }}
          MODERATOR_BDUSS_INDEX: ${{ secrets.MODERATOR_BDUSS_INDEX }}
          TARGET_POST_IDS: ${{ secrets.TARGET_POST_IDS }}
          MODERATOR_TASK_ENABLE:    "true"   # 吧主任务
          MODERATOR_POST_ENABLE:    "true"  # 回复任务
          MODERATOR_TOP_ENABLE:     "false"   # 置顶任务
          MODERATOR_DELETE_ENABLE:  "false"  # 删除回复
          PROXY_ENABLE: "true"  # 启用代理
          SOCKS_PROXY:  ${{ secrets.SOCKS_PROXY }}
        run: python main.py
      - name: Append Success Log  # 追加成功日志
        run: |
          echo "$(date +%Y-%m-%d\ %H:%M:%S) - 签到成功" >> run.log
      - name: Upload log  # 上传日志
        if: always() # 确保总是执行
        uses: actions/upload-artifact@v4
        with:
          name: logs
          path: run.log
      - name: Push log  # 更新日志
        if: always() # 确保总是执行
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: auto-checkin
          branch: main
